from django.urls import path
from .views import (
    ClienteLoginView,
    DashboardClienteView,
    DashboardAdministradorView,
    DashboardRecepcionistaView,
    DashboardVeterinarioView,
    vet_disponibilidad_api,
    vet_disponibilidad_detail_api,
    vet_bloquear_dia_api,
    vet_citas_api,
    vet_cita_estado_api,
    recep_clientes_api,
    recep_cliente_detalle_api,
    recep_mascotas_api,
    recep_servicios_api,
    recep_veterinarios_api,
    recep_disponibilidad_api,
    recep_cita_create_api,
    recep_citas_hoy_api,
    recep_cita_estado_api,
    recep_replanificar_alertas_api,
    recep_replanificar_disponibilidad_api,
    recep_replanificar_cita_api,
    recep_historial_citas_cliente_api,
    LoginSelectorView,
    PersonalLoginView,
    logout_view,
    registro_clientes_view,
)

app_name = "usuarios"

urlpatterns = [
    path("login/", LoginSelectorView.as_view(), name="login_selector"),
    path("login/personal/", PersonalLoginView.as_view(), name="login_personal"),
    path("login/clientes/", ClienteLoginView.as_view(), name="login_clientes"),
    path("registro/clientes/", registro_clientes_view, name="registro_clientes"),
    path("logout/", logout_view, name="logout"),
    path("dashboard/cliente/", DashboardClienteView.as_view(), name="dashboard_cliente"),
    path("dashboard/recepcionista/", DashboardRecepcionistaView.as_view(), name="dashboard_recepcionista"),
    path("dashboard/veterinario/", DashboardVeterinarioView.as_view(), name="dashboard_veterinario"),
    path("dashboard/administrador/", DashboardAdministradorView.as_view(), name="dashboard_administrador"),
    # API Veterinario
    path("api/veterinario/disponibilidad/", vet_disponibilidad_api, name="vet_disponibilidad_api"),
    path("api/veterinario/disponibilidad/<int:pk>/", vet_disponibilidad_detail_api, name="vet_disponibilidad_detail_api"),
    path("api/veterinario/disponibilidad/bloquear-dia/", vet_bloquear_dia_api, name="vet_bloquear_dia_api"),
    path("api/veterinario/citas/", vet_citas_api, name="vet_citas_api"),
    path("api/veterinario/citas/<int:pk>/estado/", vet_cita_estado_api, name="vet_cita_estado_api"),
    # API Recepcionista
    path("api/recep/clientes/", recep_clientes_api, name="recep_clientes_api"),
    path("api/recep/clientes/<int:cliente_id>/", recep_cliente_detalle_api, name="recep_cliente_detalle_api"),
    path("api/recep/clientes/<int:cliente_id>/mascotas/", recep_mascotas_api, name="recep_mascotas_api"),
    path("api/recep/servicios/", recep_servicios_api, name="recep_servicios_api"),
    path("api/recep/veterinarios/", recep_veterinarios_api, name="recep_veterinarios_api"),
    path("api/recep/disponibilidad/", recep_disponibilidad_api, name="recep_disponibilidad_api"),
    path("api/recep/citas/", recep_cita_create_api, name="recep_cita_create_api"),
    path("api/recep/citas/hoy/", recep_citas_hoy_api, name="recep_citas_hoy_api"),
    path("api/recep/citas/<int:pk>/estado/", recep_cita_estado_api, name="recep_cita_estado_api"),
    path("api/recep/replanificar/alertas/", recep_replanificar_alertas_api, name="recep_replanificar_alertas_api"),
    path("api/recep/replanificar/disponibilidad/", recep_replanificar_disponibilidad_api, name="recep_replanificar_disponibilidad_api"),
    path("api/recep/replanificar/cita/", recep_replanificar_cita_api, name="recep_replanificar_cita_api"),
    path("api/recep/clientes/<int:cliente_id>/historial/", recep_historial_citas_cliente_api, name="recep_historial_citas_cliente_api"),
]
