# Generated by Django 5.2.5 on 2025-11-27 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_administrador_empresa_representante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('pez', 'Pez'), ('pajaro', 'Pajaro'), ('reptil', 'Reptil'), ('anfibio', 'Anfibio'), ('conejo', 'Conejo'), ('liebre', 'Liebre'), ('hamster', 'Hamster'), ('huron', 'Huron'), ('erizo', 'Erizo'), ('otro', 'Otro')], max_length=20)),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20)),
                ('edad_aproximada', models.PositiveIntegerField(blank=True, null=True)),
                ('senas_particulares', models.TextField(blank=True)),
                ('raza', models.CharField(blank=True, max_length=120)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('tiene_ficha_clinica', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='usuarios.cliente')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
            },
        ),
    ]
