# Generated by Django 5.2.5 on 2025-11-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_mascota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('consultas', 'Consultas y preventivos'), ('urgencias', 'Urgencias'), ('vacunas', 'Vacunas y desparasitaciÃ³n'), ('grooming', 'Grooming y bienestar'), ('procedimientos', 'Procedimientos / hospitalizaciÃ³n'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('precio_referencial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidad_precio', models.CharField(blank=True, help_text='Ej: por visita, por dosis, por dÃ­a', max_length=50)),
                ('duracion_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('destacado', models.BooleanField(default=False)),
                ('etiquetas', models.CharField(blank=True, help_text='Separar con comas (ej: incluye certificado, 24/7)', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='tiene_ficha_clinica',
        ),
        migrations.AddField(
            model_name='mascota',
            name='estado_reproductivo',
            field=models.CharField(choices=[('sin_castrar', 'Sin castrar'), ('esterilizado', 'Esterilizado'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20),
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='microchip',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
