# Generated by Django 5.2.5 on 2025-11-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_servicio_remove_mascota_tiene_ficha_clinica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('consultas', 'Consultas y preventivos'), ('urgencias', 'Urgencias'), ('vacunas', 'Vacunas y desparasitación'), ('grooming', 'Grooming y bienestar'), ('procedimientos', 'Procedimientos / hospitalización'), ('otro', 'Otro')], default='otro', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='unidad_precio',
            field=models.CharField(blank=True, help_text='Ej: por visita, por dosis, por día', max_length=50),
        ),
    ]
