# Generated by Django 5.2.5 on 2025-11-27 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_servicio_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seccion de Servicio',
                'verbose_name_plural': 'Secciones de Servicios',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='usuarios.servicioseccion'),
        ),
    ]
