# Generated by Django 5.2.5 on 2025-11-27 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_servicioseccion_servicio_seccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='categoria',
        ),
    ]
