# Generated by Django 5.2.5 on 2025-11-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_remove_servicio_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='estado_reproductivo',
            field=models.CharField(choices=[('sin_castrar', 'Sin esterilizar'), ('esterilizado', 'Esterilizado'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20),
        ),
    ]
