# Generated by Django 5.2.5 on 2025-11-28 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0010_remove_servicio_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadVeterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No disponible'), ('bloqueado', 'Bloqueado')], default='disponible', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='usuarios.veterinario')),
            ],
            options={
                'verbose_name': 'Disponibilidad de Veterinario',
                'verbose_name_plural': 'Disponibilidades de Veterinario',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DiaBloqueadoVeterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('razon', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_bloqueados', to='usuarios.veterinario')),
            ],
            options={
                'verbose_name': 'Dia bloqueado',
                'verbose_name_plural': 'Dias bloqueados',
                'ordering': ['-fecha'],
                'unique_together': {('veterinario', 'fecha')},
            },
        ),
    ]
